### ISSUE TITLE
Error during the books import 

### ISSUE THREAD

**Issue by sarapeddy** [ilmercatinodellibro/ilmercatinodellibro#43]
During the books import, following the instruction, when running 'import:books' script an error occurs.

```bash
Mercatino del Libro Commands booting...
Starting Nest application... NestFactory
CommandRootModule dependencies initialized InstanceLoader
ImportBooksModule dependencies initialized InstanceLoader
DiscoveryModule dependencies initialized InstanceLoader
CommandRunnerModule dependencies initialized InstanceLoader
Importing books...
Cannot load books, error:  Error: Unable to process and import the books from the source file.
    at ImportBooksCommand.loadBooks (/home/p-caleffi/Documenti/source/ilmercatinodellibro/packages/server/dist/src/modules/book/import-books.command.js:61:23)
    at async ImportBooksCommand.run (/home/p-caleffi/Documenti/source/ilmercatinodellibro/packages/server/dist/src/modules/book/import-books.command.js:45:17)
    at async Command.<anonymous> (/home/p-caleffi/Documenti/source/ilmercatinodellibro/node_modules/.pnpm/nest-commander@3.12.5_@nestjs+common@10.2.7_@nestjs+core@10.2.7_@types+inquirer@8.2.10_typescript@5.4.4/node_modules/nest-commander/src/command-runner.service.js:156:24)
    at async Command.parseAsync (/home/p-caleffi/Documenti/source/ilmercatinodellibro/node_modules/.pnpm/commander@11.1.0/node_modules/commander/lib/command.js:936:5)
    at async CommandRunnerService.run (/home/p-caleffi/Documenti/source/ilmercatinodellibro/node_modules/.pnpm/nest-commander@3.12.5_@nestjs+common@10.2.7_@nestjs+core@10.2.7_@types+inquirer@8.2.10_typescript@5.4.4/node_modules/nest-commander/src/command-runner.service.js:196:9)
    at async CommandFactory.runApplication (/home/p-caleffi/Documenti/source/ilmercatinodellibro/node_modules/.pnpm/nest-commander@3.12.5_@nestjs+common@10.2.7_@nestjs+core@10.2.7_@types+inquirer@8.2.10_typescript@5.4.4/node_modules/nest-commander/src/command.factory.js:37:9)
    at async CommandFactory.run (/home/p-caleffi/Documenti/source/ilmercatinodellibro/node_modules/.pnpm/nest-commander@3.12.5_@nestjs+common@10.2.7_@nestjs+core@10.2.7_@types+inquirer@8.2.10_typescript@5.4.4/node_modules/nest-commander/src/command.factory.js:13:9)
    at async bootstrap (/home/p-caleffi/Documenti/source/ilmercatinodellibro/packages/server/dist/src/commander.js:7:5)
```

Note that some files are correctly generated, but the error is so generic that it's not clear what the problem is

**Comment by IlCallo** [comment]
This is due to an undocumented step in the README, the `OS_FILESYSTEM_PATH` env variable should be set to the local path of the `/tmp-files`

We need to document it and possibly set a set a sensible default (`/packages/server/tmp-files` if relative paths are usable) so that people can skip that step altogether

**Comment by IlCallo** [comment]
I just tested on Linux that adding `./tmp-files` as default value for `OS_FILESYSTEM_PATH` correctly references the folder in `packages/server/tmp-files`

@SirAuron

**Comment by SirAuron** [comment]
Updated according to suggested changes. Closing this issue.
